namespace: cloin
name: prometheus
version: 0.1.0
readme: README.md
authors:
  - Colin McNaughton <@cloin>
description: Basic Prometheus collection
license_file: 'LICENSE'
tags:
  - infrastructure
  - observability
dependencies: {}
repository: https://github.com/cloin/cloin.prometheus
documentation: https://github.com/cloin/cloin.prometheus/tree/main/docs
issues: https://github.com/cloin/cloin.prometheus/issues
build_ignore: []